spring:
  datasource:
    url: jdbc:mysql://localhost:3306/promotion
    username: hello
    password: hello
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: your_super_secret_key_which_is_very_long
  expiration: 86400000